# Build script with automatic version increment
# This script updates version.py before building with PyInstaller

param(
    [string]$Branch = "main"
)

Write-Host "===== IntelAvatar Build Script with Version Control =====" -ForegroundColor Cyan

# Get git information
Write-Host "`nGetting version information from git..." -ForegroundColor Yellow

try {
    # Get commit count on main branch
    $commitCount = git rev-list --count $Branch
    $version = "1.0.$commitCount"
    
    # Get short commit hash
    $gitHash = git rev-parse --short HEAD
    
    # Get current branch
    $currentBranch = git rev-parse --abbrev-ref HEAD
    
    # Get current date
    $buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    
    Write-Host "Version: $version" -ForegroundColor Green
    Write-Host "Git Hash: $gitHash" -ForegroundColor Green
    Write-Host "Branch: $currentBranch" -ForegroundColor Green
    Write-Host "Build Date: $buildDate" -ForegroundColor Green
    
} catch {
    Write-Host "Error getting git information. Using defaults." -ForegroundColor Red
    $version = "1.0.0"
    $gitHash = "unknown"
    $currentBranch = "unknown"
    $buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
}

# Update version.py
Write-Host "`nUpdating configs/version.py..." -ForegroundColor Yellow

$versionContent = @"
"""
Version information for IntelAvatar.
This file is auto-generated by the build script.
"""

__version__ = "$version"
BUILD_DATE = "$buildDate"
GIT_HASH = "$gitHash"
GIT_BRANCH = "$currentBranch"
"@

Set-Content -Path "configs/version.py" -Value $versionContent -Encoding UTF8
Write-Host "Version file updated successfully!" -ForegroundColor Green

# Update version_info.txt for exe metadata
Write-Host "`nUpdating version_info.txt for exe metadata..." -ForegroundColor Yellow

$versionParts = $version -split '\.'
$major = $versionParts[0]
$minor = $versionParts[1]
$patch = if ($versionParts.Length -gt 2 -and $versionParts[2]) { $versionParts[2] } else { "0" }

$versionInfoContent = @"
# UTF-8
#
# For more details about fixed file info 'ffi' see:
# http://msdn.microsoft.com/en-us/library/ms646997.aspx
VSVersionInfo(
  ffi=FixedFileInfo(
    # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)
    # Set not needed items to zero 0.
    filevers=($major, $minor, $patch, 0),
    prodvers=($major, $minor, $patch, 0),
    # Contains a bitmask that specifies the valid bits 'flags'r
    mask=0x3f,
    # Contains a bitmask that specifies the Boolean attributes of the file.
    flags=0x0,
    # The operating system for which this file was designed.
    # 0x4 - NT and there is no need to change it.
    OS=0x40004,
    # The general type of file.
    # 0x1 - the file is an application.
    fileType=0x1,
    # The function of the file.
    # 0x0 - the function is not defined for this fileType
    subtype=0x0,
    # Creation date and time stamp.
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'Intel Corporation'),
        StringStruct(u'FileDescription', u'IntelAvatar - Wireless CE Log Analysis Tool'),
        StringStruct(u'FileVersion', u'$version.0'),
        StringStruct(u'InternalName', u'IntelAvatar'),
        StringStruct(u'LegalCopyright', u'Copyright `u00a9 2026 Intel Corporation'),
        StringStruct(u'OriginalFilename', u'IntelAvatar.exe'),
        StringStruct(u'ProductName', u'IntelAvatar'),
        StringStruct(u'ProductVersion', u'$version.0'),
        StringStruct(u'Comments', u'Git: $gitHash | Build: $buildDate')])
      ]), 
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"@

Set-Content -Path "version_info.txt" -Value $versionInfoContent -Encoding UTF8
Write-Host "version_info.txt updated successfully!" -ForegroundColor Green

# Build with PyInstaller
Write-Host "`nBuilding with PyInstaller..." -ForegroundColor Yellow

try {
    # Check if requirements are installed
    Write-Host "Installing/checking requirements..." -ForegroundColor Yellow
    pip install -r requirements.txt -q
    
    # Run PyInstaller
    Write-Host "Running PyInstaller..." -ForegroundColor Yellow
    pyinstaller IntelAvatar.spec
    
    # Rename exe with version
    Write-Host "Renaming executable with version..." -ForegroundColor Yellow
    $exePath = "dist/IntelAvatar/IntelAvatar.exe"
    $newExePath = "dist/IntelAvatar/IntelAvatar_v${version}_${gitHash}.exe"
    
    if (Test-Path $exePath) {
        Move-Item -Path $exePath -Destination $newExePath -Force
        Write-Host "Renamed to: IntelAvatar_v${version}_${gitHash}.exe" -ForegroundColor Green
    }
    
    Write-Host "`n===== Build Complete! =====" -ForegroundColor Green
    Write-Host "Version: $version" -ForegroundColor Cyan
    Write-Host "Git Hash: $gitHash" -ForegroundColor Cyan
    Write-Host "Executable: IntelAvatar_v${version}_${gitHash}.exe" -ForegroundColor Cyan
    Write-Host "Output location: dist/IntelAvatar/" -ForegroundColor Cyan
    
} catch {
    Write-Host "`nBuild failed: $_" -ForegroundColor Red
    exit 1
}
