"""
Comment-draft composer: turns a CaseAnalysis into the IPS comment text.

Two renderings:
  * plain  — what the reviewer edits in the queue UI (also the Selenium
             fallback paste body)
  * html   — rich-text for the REST field Core_IPS_Rich_Comment__c

Every draft carries AI_MARKER so the ledger / prior-comment scan can detect
our own posts and never double-comment a case.
"""

from __future__ import annotations

import html as _html
from typing import Optional

from .runner import CaseAnalysis, IncidentReport

AI_MARKER = "[AI-Avatar preliminary analysis]"
_FOOTER = ("Generated by Intel Wireless CE Avatar (AI). "
           "Please verify before sharing conclusions with the customer.")


def _norm_key(k: str) -> str:
    """Normalize a JSON key for tolerant lookup: the triage LLM oscillates
    between 'Issue summary' / 'Issue_summary' / 'issue summary' etc."""
    return "".join(ch for ch in str(k).lower() if ch.isalnum())


def _get_norm(d: dict, key: str):
    """Fetch d[key] tolerating spacing/underscore/case variations."""
    if not isinstance(d, dict):
        return None
    want = _norm_key(key)
    for k, v in d.items():
        if _norm_key(k) == want:
            return v
    return None


def _triage_sections(triage: dict) -> list[tuple[str, list[str]]]:
    """Flatten the analyze_desc JSON into (title, lines) sections."""
    out: list[tuple[str, list[str]]] = []
    summary = _get_norm(triage, "Issue summary") or {}
    if isinstance(summary, dict):
        for key in ("Symptom", "Repro Steps", "Other Information"):
            val = _get_norm(summary, key)
            if isinstance(val, list) and val:
                out.append((key, [str(v) for v in val if str(v).strip()]))
            elif isinstance(val, str) and val.strip():
                out.append((key, [val.strip()]))
    action = _get_norm(triage, "Next action") or {}
    if isinstance(action, dict):
        rec = _get_norm(action, "Recommendation")
        if isinstance(rec, list) and rec:
            out.append(("Recommended next steps / questions",
                        [str(v) for v in rec if str(v).strip()]))
        elif isinstance(rec, str) and rec.strip():
            out.append(("Recommended next steps / questions", [rec.strip()]))
    return out


def _incident_lines(inc: IncidentReport) -> list[str]:
    lines: list[str] = []
    rep = inc.report or {}
    if inc.issue_time:
        lines.append(f"Incident time: {inc.issue_time}")
    if rep.get("root_cause_summary"):
        lines.append(f"Root cause: {rep['root_cause_summary']}")
    if rep.get("confidence_score") is not None:
        lines.append(f"Confidence: {rep['confidence_score']}/100")
    skills = rep.get("involved_skills") or []
    if skills:
        lines.append("Analysis areas: " + ", ".join(str(s) for s in skills))
    actions = rep.get("recommended_actions") or []
    if actions:
        lines.append("Recommended actions:")
        lines.extend(f"  - {a}" for a in actions)
    return lines


def compose_plain(analysis: CaseAnalysis) -> str:
    """Plain-text draft (editable in the review UI)."""
    parts: list[str] = [AI_MARKER, ""]

    if analysis.mode == "full" and analysis.incidents:
        parts.append(f"Automated log analysis for case {analysis.case_nbr}"
                     + (f" — {analysis.subject}" if analysis.subject else ""))
        if analysis.issue_type:
            parts.append(f"Issue classification: {analysis.issue_type}")
        parts.append("")
        reported = [i for i in analysis.incidents if i.report]
        for n, inc in enumerate(reported, 1):
            if len(reported) > 1:
                parts.append(f"--- Incident {n}/{len(reported)} ---")
            parts.extend(_incident_lines(inc))
            md = (inc.report or {}).get("markdown_summary") or ""
            if md:
                parts.append("")
                parts.append(md.strip())
            parts.append("")
    else:
        # Triage-only: description-level assessment + what we need from the OEM.
        parts.append(f"Automated triage for case {analysis.case_nbr}"
                     + (f" — {analysis.subject}" if analysis.subject else ""))
        if analysis.issue_type:
            parts.append(f"Issue classification: {analysis.issue_type}")
        if analysis.error:
            parts.append(f"(Full log analysis not run: {analysis.error})")
        parts.append("")
        for title, lines in _triage_sections(analysis.triage):
            parts.append(f"{title}:")
            parts.extend(f"  - {ln}" for ln in lines)
            parts.append("")

    parts.append(_FOOTER)
    # Collapse accidental double blank lines.
    text = "\n".join(parts)
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    return text.strip() + "\n"


def compose_html(plain_text: str) -> str:
    """Rich-text rendering for Core_IPS_Rich_Comment__c: escape + <br/>.
    (Salesforce rich text accepts a limited HTML subset; simple line breaks
    keep the plain and rich renderings identical after human edits.)"""
    escaped = _html.escape(plain_text)
    return "<p>" + escaped.replace("\n", "<br/>") + "</p>"


def compose(analysis: CaseAnalysis) -> dict:
    """Returns {"plain": str, "html": str, "confidence": int|None}."""
    plain = compose_plain(analysis)
    best = analysis.best_incident
    return {
        "plain": plain,
        "html": compose_html(plain),
        "confidence": best.confidence if best else None,
    }
